# https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ov

# We want to use Cellranger to 
# (1) map sequence reads to the human genome GRCm38; and 
# (2) perform the UMI and gene-level counts against Ensembl gene model <V100>
#
# First, pick out and make a txt file for 10X datasets
# Second, find number of cells (in metadata?)
# Follow cellranger tutorial https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ct

##need to rename your fastq files so tha they fit this format.
#_L00#_  represents lane number
# mv  SRR8111691_1.fastq.gz SRR8111691_S1_L001_R1_001.fastq.gz
# mv  SRR8111691_2.fastq.gz SRR8111691_S1_L001_R2_001.fastq.gz
# https://bioinformaticsworkbook.org/dataAnalysis/RNA-Seq/Single_Cell_RNAseq/Chromium_Cell_Ranger.html#gsc.tab=0

# read this https://kb.10xgenomics.com/hc/en-us/articles/115003802691-How-do-I-prepare-Sequence-Read-Archive-SRA-data-from-NCBI-for-Cell-Ranger-

# HypoMap:
# For 10X datasets (including nucSeq), Cellranger Version 6.0.1 (5.0.1 for nucSeq) was used to 
# (1) map sequence reads to the mouse genome GRCm38 (mm10); and 
# (2) perform the UMI and gene-level counts against Ensembl gene model V100, with Gm28040 removed to recover Kiss1 expression. 
# The per-cell gene count tables (in HDF5) generated by the software were then used for downstream analyses.

# Example
REF_GENOMES=$1  # Reference genomes directory
PROJECT=PRJNA421274
READ=SRR6350505
N_CELLS=3000

REF=$REF_GENOMES/homo_sapiens/10xgenomics

# Load modules
module load CellRanger/7.1.0

# mkdir -p "$REF"
wget https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz -P "$REF"

# Download reference file (this takes a while)
tar -xvf "$REF"/refdata-gex-GRCh38-2020-A.tar.gz 
rm "$REF"/refdata-gex-GRCh38-2020-A.tar.gz

# https://emea.support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-20-software-guide-15051736-03.pdf
# Go to page 17

# cd PRJNA879764
# mkdir logs
# nohup cat PRJNA879764_SraAccList.txt | parallel fasterq-dump sra_files/{} --include-technical -S -O raw_reads3 &> logs/output_fq.out &  #done 
# nohup cat PRJNA879764_SraAccList.txt | parallel gzip raw_reads/{}*.fastq &  # done
# ps -xw

# Page for length of R1 and R2
# https://www.10xgenomics.com/support/single-cell-gene-expression/documentation/steps/sequencing/sequencing-requirements-for-single-cell-3

# --sample $READ excluded as we want to use all (S1)
# Run cellranger to align and quantify
cellranger count --id run_count_"$PROJECT" --transcriptome ../"$REF"/refdata-gex-GRCh38-2020-A.tar.gz \
                 --fastqs "$PROJECT"/raw_reads  \
                 
     
