# https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ov

# We want to use Cellranger to 
# (1) map sequence reads to the human genome GRCm38; and 
# (2) perform the UMI and gene-level counts against Ensembl gene model <V100>
#
# First, pick out and make a txt file for 10X datasets
# Second, find number of cells (in metadata?)
# Follow cellranger tutorial https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_ct

##need to rename your fastq files so tha they fit this format.
#_L00#_  represents lane number
# mv  SRR8111691_1.fastq.gz SRR8111691_S1_L001_R1_001.fastq.gz
# mv  SRR8111691_2.fastq.gz SRR8111691_S1_L001_R2_001.fastq.gz
# mv  SRR8111692_1.fastq.gz SRR8111692_S1_L002_R1_001.fastq.gz
# mv  SRR8111692_2.fastq.gz SRR8111692_S1_L002_R2_001.fastq.gz
# mv  SRR8111693_1.fastq.gz SRR8111693_S1_L003_R1_001.fastq.gz
# mv  SRR8111693_2.fastq.gz SRR8111693_S1_L003_R2_001.fastq.gz
# mv  SRR8111694_1.fastq.gz SRR8111694_S1_L004_R1_001.fastq.gz
# mv  SRR8111694_2.fastq.gz SRR8111694_S1_L004_R2_001.fastq.gz
# https://bioinformaticsworkbook.org/dataAnalysis/RNA-Seq/Single_Cell_RNAseq/Chromium_Cell_Ranger.html#gsc.tab=0

# read this https://kb.10xgenomics.com/hc/en-us/articles/115003802691-How-do-I-prepare-Sequence-Read-Archive-SRA-data-from-NCBI-for-Cell-Ranger-

# HypoMap:
# For 10X datasets (including nucSeq), Cellranger Version 6.0.1 (5.0.1 for nucSeq) was used to 
# (1) map sequence reads to the mouse genome GRCm38 (mm10); and 
# (2) perform the UMI and gene-level counts against Ensembl gene model V100, with Gm28040 removed to recover Kiss1 expression. 
# The per-cell gene count tables (in HDF5) generated by the software were then used for downstream analyses.

# Example
REF_GENOMES=$1  # Reference genomes directory
PROJECT=PRJNA421274
READ=SRR6350505
N_CELLS=3000

REF=$REF_GENOMES/homo_sapiens/10xgenomics

# Load modules
module load CellRanger/7.1.0

# mkdir -p "$REF"
wget https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz -P "$REF"

# Download reference file (this takes a while)
tar -xvf "$REF"/refdata-gex-GRCh38-2020-A.tar.gz 
rm "$REF"/refdata-gex-GRCh38-2020-A.tar.gz

# Extract the lane number or fastq files that have multiple runs per sample
zcat SRR16093329_2.fastq.gz | awk -F: '{print $4}' | head -1

# Run cellranger to align and quantify
cellranger count --id "$PROJECT" --transcriptome "$REF"/refdata-gex-GRCh38-2020-A.tar.gz \
                 --fastqs "$PROJECT"/raw_reads --sample $READ \
                 --expect_cells "$N_CELLS" 
                 
     
